### ISSUE TITLE
Documentation is not created

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-servicemanager-migration#32]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | current / all

#### Summary

The content for the documentation is [present](https://github.com/laminas/laminas-servicemanager-migration/blob/0.1.x/docs/book/v1/intro.md) but not created.

#### Current behavior

The documentation is missing under https://docs.laminas.dev/laminas-servicemanager-migration/
A 404 error is produced.

#### How to reproduce

https://docs.laminas.dev/laminas-servicemanager-migration/

#### Expected behavior

The documentation can be accessed and read.

---

I will create a pull request to fix the problem.

**Comment by froschdesign** [comment]
@samsonasik 
Can you create an empty branch with name `gh-pages` for the documentation?
Thanks in advance! 👍

**Comment by samsonasik** [comment]
@froschdesign I created gh-pages branch https://github.com/laminas/laminas-servicemanager-migration/tree/gh-pages

**Comment by froschdesign** [comment]
I have checked the related repository settings and it now looks good.

**Comment by froschdesign** [comment]
A deploy key is missing: https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys

https://github.com/laminas/laminas-servicemanager-migration/runs/5232086453?check_suite_focus=true#step:3:11

**Comment by samsonasik** [comment]
How to update it?

**Comment by froschdesign** [comment]
@weierophinney 
Can you help here?
Thanks in advance! 👍

**Comment by weierophinney** [comment]
We don't use deploy keys for this; it's a PAT that is used first to check out the repo, and then push to the gh-pages branch.

I'm getting an increasing number of these, and I'm not sure what's going on. In most cases, no configuration has changed, nor has the docs-deploy action changed. I'm honestly unsure how to fix or address it. :frowning_face:

**Comment by froschdesign** [comment]
Fixed with #100
